# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_camera_setup.ipynb.

# %% auto #0
__all__ = ['set_cam_format_fourcc', 'get_cam_format_fourcc', 'set_cam_resolution', 'get_cam_resolution', 'CameraNode', 'main']

# %% ../nbs/01_camera_setup.ipynb #a3813c0b
import sys
import rclpy
from rclpy.node import Node
from rclpy.executors import ExternalShutdownException
import cv2
from cv_bridge import CvBridge
from sensor_msgs.msg import Image
import numpy as np
import matplotlib.pyplot as plt

# %% ../nbs/01_camera_setup.ipynb #9e99933c
def set_cam_format_fourcc(cam, format='MJPG'):
    "Set Pixel or Compression format"
    # Options include 'MJPG', 'YUYV', 'RGB3', etc. Check your camera documentation for supported formats.
    # Check that the format is valid, otherwise return an error message
    valid_formats = ['MJPG', 'YUYV', 'RGB3', 'GRAY', 'YUV420P', 'NV12', 'NV21']
    if format not in valid_formats:
        raise ValueError(f"Invalid format '{format}'. Valid formats are: {valid_formats}")

    # Set the camera to output raw frames (uncompressed)
    cam.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter_fourcc(*format))

def get_cam_format_fourcc(cam):
    "Get the current Pixel or Compression format"
    codec_int = int(cam.get(cv2.CAP_PROP_FOURCC))
    codec_str = "".join([chr((codec_int >> 8 * i) & 0xFF) for i in range(4)])
    return codec_str

def set_cam_resolution(cam, width=640, height=480):
    "Set the resolution of the camera feed"
    cam.set(cv2.CAP_PROP_FRAME_WIDTH, width)
    cam.set(cv2.CAP_PROP_FRAME_HEIGHT, height)

def get_cam_resolution(cam):
    "Get the current resolution of the camera feed"
    width = int(cam.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cam.get(cv2.CAP_PROP_FRAME_HEIGHT))
    return width, height


# %% ../nbs/01_camera_setup.ipynb #8b76b624
class CameraNode(Node):
    def __init__(self):
        super().__init__('camera_node')
        
        # 1. Declare the parameter with a default value (0 = default USB cam)
        # We use a string default so it can accept "0" or "http://..."
        self.declare_parameter('video_source', '0')
        self.declare_parameter('frame_rate', 30.0)
        self.declare_parameter('topic_name', '/camera/image_raw')
        self.declare_parameter('video_fourcc', 'MJPG')
        self.declare_parameter('resolution_width', 640)
        self.declare_parameter('resolution_height', 480)
        
        # 2. Get the parameter value
        self.source = self.get_parameter('video_source').value
        self.frame_rate = self.get_parameter('frame_rate').value
        self.topic_name = self.get_parameter('topic_name').value
        self.fourcc = self.get_parameter('video_fourcc').value
        self.resolution = (
            self.get_parameter('resolution_width').value,
            self.get_parameter('resolution_height').value
        )

        assert isinstance(self.source, str), "video_source parameter must be a string"
        assert isinstance(self.frame_rate, (int, float)), 'frame_rate must be a number'
        assert isinstance(self.topic_name, str), 'topic_name must be a string'
        assert isinstance(self.fourcc, str), 'FOURCC must be a string'
        assert isinstance(self.resolution, tuple) and len(self.resolution) == 2, 'resolution must be a tuple of two elements'

        # 3. Open the camera or video source
        if self.source.isdigit():
            self.cap = cv2.VideoCapture(int(self.source))
        else:
            self.cap = cv2.VideoCapture(self.source)

        if not self.cap.isOpened():
            self.get_logger().error(f"Failed to open source: {self.source}")
            raise RuntimeError('Could not open video source')

        # Publisher
        self.queueSize = 20
        self.publisher_ = self.create_publisher(Image, self.topic_name, self.queueSize)

        # Timer to publish at the desired frequency
        timer_period = 1.0 / self.frame_rate
        self.timer = self.create_timer(timer_period, self.timer_callback)

        # Set compression of the image (critical for WSL timeouts)
        set_cam_format_fourcc(self.cap, format=self.fourcc)

        # CvBridge for converting OpenCV images to ROS2 Image messages
        self.bridge = CvBridge()
        self.get_logger().info(
            f'Publ. img at {self.frame_rate} FPS, from source {self.source} on "{self.topic_name}" '
        )

        # Frame counter for logging
        self.frame_count = 0

    # Timer callback to capture and publish frames
    def timer_callback(self):
        ''' 
        Timer callback to capture and publish frames
            - Captures a frame from the camera
            - Resizes it if necessary to the specified resolution
            - Converts it to a ROS2 Image message using CvBridge
            - Publishes it on the specified topic
            - Logs the published frame count
        '''
        ret, frame = self.cap.read()
        if not ret:
            self.get_logger().warn('Failed to read frame from camera')
            return
        
        # resize the image
        if (frame.shape[1], frame.shape[0]) != self.resolution:
            frame = cv2.resize(frame, self.resolution, interpolation=cv2.INTER_CUBIC)


        # Transform the OpenCV BGR image to a ROS2 Image message
        msg = self.bridge.cv2_to_imgmsg(frame, encoding='bgr8')

        # Optional
        # msg.header.stamp = self.get_clock().now().to_msg()
        # msg.header.frame_id = 'camera_frame'
        self.publisher_.publish(msg)

        # Log
        if self.frame_count % 10 == 0:  # Log every 10 frames
            self.get_logger().info(f'Published frame {self.frame_count}')
        
        self.frame_count += 1

    def destroy_node(self):
        self.cap.release()
        super().destroy_node()
            

# %% ../nbs/01_camera_setup.ipynb #31b45876
def main(args=None):
    rclpy.init(args=args)
    node = CameraNode()

    try:
        rclpy.spin(node)
    except (KeyboardInterrupt, ExternalShutdownException):
        node.get_logger().info('Node stopped by user or external shutdown')
    finally:
        node.destroy_node()
        rclpy.try_shutdown()



# %% ../nbs/01_camera_setup.ipynb #3784fae8
if not hasattr(sys, 'ps1'):  # True si no estamos en el REPL (o notebook)
    if __name__=="__main__":
        main()
